// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example3.proto

export class Donkey {
  hi: string;

  constructor() {
    this.hi = "";
  }
}

export class Funky {
  monkey: number;
  dokey: number;

  constructor() {
    this.monkey = 0;
    this.dokey = 0;
  }
}

