"use strict";
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example2.proto
exports.__esModule = true;
var example2 = /** @class */ (function () {
    function example2() {
        this.zomg = 0;
    }
    return example2;
}());
exports.example2 = example2;
var refexample3 = /** @class */ (function () {
    function refexample3() {
        this.funky = 0;
    }
    return refexample3;
}());
exports.refexample3 = refexample3;
