"use strict";
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example3.proto
exports.__esModule = true;
var Donkey = /** @class */ (function () {
    function Donkey() {
        this.hi = "";
    }
    return Donkey;
}());
exports.Donkey = Donkey;
var Funky = /** @class */ (function () {
    function Funky() {
        this.monkey = 0;
        this.dokey = 0;
    }
    return Funky;
}());
exports.Funky = Funky;
