// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example1.proto

import * as ___example2_pb from "./example2_pb"


export const enum AEnum1 {
  A = 0,
  B = 2,
}

export class example2 {
  aint32: number;

  constructor() {
    this.aint32 = 0;
  }
}

export class example1 {
  adouble: number;
  afloat: number;
  aint32: number;
  aint64: number;
  auint32: number;
  auint64: number;
  asint32: number;
  asint64: number;
  afixed32: number;
  afixed64: number;
  asfixed32: number;
  asfixed64: number;
  abool: boolean;
  astring: string;
  abytes: string;
  aenum1: AEnum1;
  aenum2: example1.AEnum2;
  aenum22: ___example2_pb.AEnum2;
  manystring: string[];
  manyint64: number[];
  aexample2: example1.example2 | null;
  aexample22: example2 | null;
  aexample23: ___example2_pb.example2 | null;
  amap: Map<string, string>;
  amap2: Map<string, ___example2_pb.example2 | null>;
  outoforder: number;
  oostring: string;
  ooint: number;

  constructor() {
    this.adouble = 0.0;
    this.afloat = 0.0;
    this.aint32 = 0;
    this.aint64 = 0;
    this.auint32 = 0;
    this.auint64 = 0;
    this.asint32 = 0;
    this.asint64 = 0;
    this.afixed32 = 0;
    this.afixed64 = 0;
    this.asfixed32 = 0;
    this.asfixed64 = 0;
    this.abool = false;
    this.astring = "";
    this.abytes = "";
    this.aenum1 = 0;
    this.aenum2 = 0;
    this.aenum22 = 0;
    this.manystring = [];
    this.manyint64 = [];
    this.aexample2 = null;
    this.aexample22 = null;
    this.aexample23 = null;
    this.amap = new Map<string, string>();
    this.amap2 = new Map<string, ___example2_pb.example2 | null>();
    this.outoforder = 0;
    this.oostring = "";
    this.ooint = 0;
  }
}

export namespace example1 {
  export const enum AEnum2 {
    C = 0,
    D = 10,
  }
}

export namespace example1 {
  export class example2 {
    astring: string;

    constructor() {
      this.astring = "";
    }
  }
}

export namespace example1 {
  export class AmapEntry {
    key: string;
    value: string;

    constructor() {
      this.key = "";
      this.value = "";
    }
  }
}

export namespace example1 {
  export class Amap2Entry {
    key: string;
    value: ___example2_pb.example2 | null;

    constructor() {
      this.key = "";
      this.value = null;
    }
  }
}

