// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example2.proto

export const enum AEnum2 {
  Z = 0,
}

export class example2 {
  zomg: number;

  constructor() {
    this.zomg = 0;
  }
}

export class refexample3 {
  funky: Funky | null;

  constructor() {
    this.funky = null;
  }
}

