// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example1.proto
export class example2 {
    constructor() {
        this.aint32 = 0;
    }
}
export class example1 {
    constructor() {
        this.adouble = 0.0;
        this.afloat = 0.0;
        this.aint32 = 0;
        this.aint64 = 0n;
        this.auint32 = 0;
        this.auint64 = 0;
        this.asint32 = 0;
        this.asint64 = 0n;
        this.afixed32 = 0;
        this.afixed64 = 0n;
        this.asfixed32 = 0;
        this.asfixed64 = 0n;
        this.abool = false;
        this.astring = "";
        this.abytes = new Uint8Array(0);
        this.aenum1 = 0;
        this.aenum2 = 0;
        this.aenum22 = 0;
        this.manystring = [];
        this.manyint64 = [];
        this.aexample2 = null;
        this.aexample22 = null;
        this.aexample23 = null;
        this.amap = new Map();
        this.amap2 = new Map();
        this.outoforder = 0n;
        this.oostring = "";
        this.ooint = 0;
    }
}
(function (example1) {
    class example2 {
        constructor() {
            this.astring = "";
        }
    }
    example1.example2 = example2;
})(example1 || (example1 = {}));
(function (example1) {
    class AmapEntry {
        constructor() {
            this.key = "";
            this.value = "";
        }
    }
    example1.AmapEntry = AmapEntry;
})(example1 || (example1 = {}));
(function (example1) {
    class Amap2Entry {
        constructor() {
            this.key = "";
            this.value = null;
        }
    }
    example1.Amap2Entry = Amap2Entry;
})(example1 || (example1 = {}));
