// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example2.proto
export class example2 {
    constructor() {
        this.zomg = 0;
    }
}
export class refexample3 {
    constructor() {
        this.funky = null;
    }
}
