"use strict";
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example1.proto
exports.__esModule = true;
var example2 = /** @class */ (function () {
    function example2() {
        this.aint32 = 0;
    }
    return example2;
}());
exports.example2 = example2;
var example1 = /** @class */ (function () {
    function example1() {
        this.adouble = 0.0;
        this.afloat = 0.0;
        this.aint32 = 0;
        this.aint64 = 0;
        this.auint32 = 0;
        this.auint64 = 0;
        this.asint32 = 0;
        this.asint64 = 0;
        this.afixed32 = 0;
        this.afixed64 = 0;
        this.asfixed32 = 0;
        this.asfixed64 = 0;
        this.abool = false;
        this.astring = "";
        this.abytes = "";
        this.aenum1 = 0;
        this.aenum2 = 0;
        this.aenum22 = 0;
        this.manystring = [];
        this.manyint64 = [];
        this.aexample2 = 0;
        this.aexample22 = 0;
        this.aexample23 = 0;
        this.amap = new Map();
        this.amap2 = new Map();
        this.outoforder = 0;
        this.oostring = "";
        this.ooint = 0;
        this.anany = 0;
    }
    return example1;
}());
exports.example1 = example1;
