// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example3.proto

import * as __pb__ from "../../lib/protobuf"


export class Donkey implements __pb__.Message {
  hi: string;

  constructor() {
    this.hi = "";
  }

  MergeFrom(d: __pb__.Internal.Decoder): void {
    while (!d.isEOF()) {
      var [fn, wt] = d.readTag();
      switch(fn) {
        case 1:
        console.log(`[PROTOC-DEBUG] reading field:1 (hi) wt:${wt}`);
        this.hi = d.readString();
        console.log(`[PROTOC-DEBUG] read field:1 (hi)`);
        break;
        default:
        console.log(`[PROTOC-DEBUG] skipping unknown field:${fn} wt:${wt}`);
        d.skipWireType(wt)
      }
    }
  }
}

export class Funky implements __pb__.Message {
  monkey: Funky.Monkey | null;
  dokey: Donkey | null;

  constructor() {
    this.monkey = null;
    this.dokey = null;
  }

  MergeFrom(d: __pb__.Internal.Decoder): void {
    while (!d.isEOF()) {
      var [fn, wt] = d.readTag();
      switch(fn) {
        case 1:
        console.log(`[PROTOC-DEBUG] reading field:1 (monkey) wt:${wt}`);
        if (this.monkey == null) this.monkey = new Funky.Monkey();
        this.monkey.MergeFrom(d.readDecoder());
        console.log(`[PROTOC-DEBUG] read field:1 (monkey)`);
        break;
        case 2:
        console.log(`[PROTOC-DEBUG] reading field:2 (dokey) wt:${wt}`);
        if (this.dokey == null) this.dokey = new Donkey();
        this.dokey.MergeFrom(d.readDecoder());
        console.log(`[PROTOC-DEBUG] read field:2 (dokey)`);
        break;
        default:
        console.log(`[PROTOC-DEBUG] skipping unknown field:${fn} wt:${wt}`);
        d.skipWireType(wt)
      }
    }
  }
}

export namespace Funky {
  export class Monkey implements __pb__.Message {
    hi: string;

    constructor() {
      this.hi = "";
    }

    MergeFrom(d: __pb__.Internal.Decoder): void {
      while (!d.isEOF()) {
        var [fn, wt] = d.readTag();
        switch(fn) {
          case 1:
          console.log(`[PROTOC-DEBUG] reading field:1 (hi) wt:${wt}`);
          this.hi = d.readString();
          console.log(`[PROTOC-DEBUG] read field:1 (hi)`);
          break;
          default:
          console.log(`[PROTOC-DEBUG] skipping unknown field:${fn} wt:${wt}`);
          d.skipWireType(wt)
        }
      }
    }
  }
}

