// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example3.proto

import * as __pb__ from "../../lib/protobuf"


export class Donkey implements __pb__.Message {
  hi: string;

  constructor() {
    this.hi = "";
  }

  MergeFrom(d: __pb__.Internal.Decoder): void {
    while (!d.isEOF()) {
      var [fn, wt] = d.readTag();
      switch(fn) {
        case 1:
        this.hi = d.readString();
        break;
        default:
        d.skipWireType(wt)
      }
    }
  }
}

export class Funky implements __pb__.Message {
  monkey: Funky.Monkey | null;
  dokey: Donkey | null;

  constructor() {
    this.monkey = null;
    this.dokey = null;
  }

  MergeFrom(d: __pb__.Internal.Decoder): void {
    while (!d.isEOF()) {
      var [fn, wt] = d.readTag();
      switch(fn) {
        case 1:
        break;
        case 2:
        break;
        default:
        d.skipWireType(wt)
      }
    }
  }
}

export namespace Funky {
  export class Monkey implements __pb__.Message {
    hi: string;

    constructor() {
      this.hi = "";
    }

    MergeFrom(d: __pb__.Internal.Decoder): void {
      while (!d.isEOF()) {
        var [fn, wt] = d.readTag();
        switch(fn) {
          case 1:
          this.hi = d.readString();
          break;
          default:
          d.skipWireType(wt)
        }
      }
    }
  }
}

