"use strict";
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example1.proto
exports.__esModule = true;
var example2 = /** @class */ (function () {
    function example2() {
        this.aint32 = 0;
    }
    return example2;
}());
exports.example2 = example2;
var example1_example2 = /** @class */ (function () {
    function example1_example2() {
        this.astring = "";
    }
    return example1_example2;
}());
exports.example1_example2 = example1_example2;
var example1_AmapEntry = /** @class */ (function () {
    function example1_AmapEntry() {
        this.key = "";
        this.value = "";
    }
    return example1_AmapEntry;
}());
exports.example1_AmapEntry = example1_AmapEntry;
var example1_Amap2Entry = /** @class */ (function () {
    function example1_Amap2Entry() {
        this.key = "";
        this.value = null;
    }
    return example1_Amap2Entry;
}());
exports.example1_Amap2Entry = example1_Amap2Entry;
var example1 = /** @class */ (function () {
    function example1() {
        this.adouble = 0.0;
        this.afloat = 0.0;
        this.aint32 = 0;
        this.aint64 = 0;
        this.auint32 = 0;
        this.auint64 = 0;
        this.asint32 = 0;
        this.asint64 = 0;
        this.afixed32 = 0;
        this.afixed64 = 0;
        this.asfixed32 = 0;
        this.asfixed64 = 0;
        this.abool = false;
        this.astring = "";
        this.abytes = "";
        this.aenum1 = 0;
        this.aenum2 = 0;
        this.aenum22 = 0;
        this.manystring = [];
        this.manyint64 = [];
        this.aexample2 = null;
        this.aexample22 = null;
        this.aexample23 = null;
        this.amap = new Map();
        this.amap2 = new Map();
        this.outoforder = 0;
        this.oostring = "";
        this.ooint = 0;
    }
    return example1;
}());
exports.example1 = example1;
