// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example3.proto
export class Donkey {
    constructor() {
        this.hi = "";
    }
}
export class Funky {
    constructor() {
        this.monkey = null;
        this.dokey = null;
    }
}
(function (Funky) {
    class Monkey {
        constructor() {
            this.hi = "";
        }
    }
    Funky.Monkey = Monkey;
})(Funky || (Funky = {}));
