// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: example1.proto

export class example2 {
  aint32: number;
}

export class example1 {
  adouble: number;
  afloat: number;
  aint32: number;
  aint64: number;
  auint32: number;
  auint64: number;
  asint32: number;
  asint64: number;
  afixed32: number;
  afixed64: number;
  asfixed32: number;
  asfixed64: number;
  abool: boolean;
  astring: string;
  abytes: string;
  aenum1: number;
  aenum2: number;
  aenum22: number;
  manystring: string[];
  manyint64: number[];
  aexample2: number;
  aexample22: number;
  aexample23: number;
  amap: number[];
  amap2: number[];
  outoforder: number;
  oostring: string;
  ooint: number;
  anany: number;
}

